### ISSUE TITLE
Segmentation fault in hyper_tune examle

### ISSUE THREAD

**Issue by mlschicker** [AlgTUDelft/pystreed#2]
Hey, 

Thank you for this excellent framework!

I wanted to try the hyper_tune functionality. 
Unfortunately, the example file (examples/gridsearch_example.py) already produces the following error: 
```
Segmentation fault (core dumped)
```
The sklearn GridSearch runs without problems.
I'm running on Ubuntu 24.04 in a newly created conda environment.
I have already tried pulling the project and recompiling it. 

Thank you!

Best, 
Maximiilan Schicker

**Comment by kjgm** [comment]
Dear Maximilian, can you provide me with more details: python version, numpy version, pandas version?

**Comment by mlschicker** [comment]
Hey, 

Thank you for your response. Sure thing.
I'm running in a conda environment. 
This is my conda export. 

Thank you!

```
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.9.24=h06a4308_0
  - expat=2.6.3=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmpdec=4.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py313h06a4308_0
  - python=3.13.0=hf623796_100_cp313
  - python_abi=3.13=0_cp313
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py313h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py313h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - ecos==2.0.14
      - joblib==1.4.2
      - numexpr==2.10.1
      - numpy==2.1.3
      - osqp==0.6.7.post3
      - pandas==2.2.3
      - pystreed==1.3.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - qdldl==0.1.7.post4
      - scikit-learn==1.5.2
      - scikit-survival==0.23.1
      - scipy==1.14.1
      - six==1.16.0
      - threadpoolctl==3.5.0
      - tzdata==2024.2
```

**Comment by kjgm** [comment]
I have been able to reproduce the bug on ubuntu with python 3.13. It seems the error had to do with the object persistence of the random number generator that was used to obtain the folds for the cross-validation. The last two [commits](https://github.com/AlgTUDelft/pystreed/commit/f2673e16197ace6815d1ef5f3cdcdfd18db18304) should solve this.

Can you rebuild from the source and check that the segmentation fault no longer happens?

**Comment by mlschicker** [comment]
Hey, thank you for the quick changes!
It seems to work now. 

Thank you! 😄
